###
GET http://localhost:4000/api/employees



###
POST http://localhost:4000/api/employees
Content-Type: application/json

{
    "name": "Ivonnessss",
    "position": "developeraaarrr"
    
}

###
GET http://localhost:4000/api/employees/602439c1a7590f2c9067d5f2


###
DELETE http://localhost:4000/api/employees/602439a5a7590f2c9067d5f1

###
PUT http://localhost:4000/api/employees/602439c1a7590f2c9067d5f2
Content-Type: application/json

{
    "name": "Alejandrass",
    "salary":10000
    
}